"""empty message

Revision ID: 66902c4164a0
Revises: 760da3cb404d
Create Date: 2025-06-11 15:42:37.350933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66902c4164a0'
down_revision = '760da3cb404d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
